#!/usr/bin/env python3.6

import argparse
import os
import subprocess
from textwrap import dedent
from sys import exit

from shared import dirs, prechecks, server_meta

meta = server_meta()

parser = argparse.ArgumentParser()
parser.add_argument(
    '-i',
    '--init',
    help='Syncs everything. Run this on initial setup',
    action='store_true')
parser.add_argument(
    '-u', '--uploads', help='Sync uploads', action='store_true')
parser.add_argument(
    '-p', '--plugins', help='Sync plugins', action='store_true')
parser.add_argument('-t', '--theme', help='Sync theme', action='store_true')
parser.add_argument(
    '-d', '--database', help='Sync database', action='store_true')
args = parser.parse_args()


def ssh_init():
    has_docker_machine = subprocess.getoutput(
        'docker-machine ls -q --filter "name={name}" | wc -l'.format(
            name=meta['name'])) == '1'
    has_ssh = subprocess.getoutput(
        'grep -c "Host {name}" ~/.ssh/config'.format(name=meta['name'])) == '1'
    if has_docker_machine:
        return ('docker-machine', 'scp -rd')
    elif has_ssh:
        return ('rsync', '-avz')
    else:
        print(
            dedent("""
        ERROR: Could not locate a docker-machine or ssh identity for {name}

        To enable SSH connections, add the following to your ~/.ssh/config file:

        Host {name}
            HostName <ip-address-of-server>
            Port 22
            User {name}
            IdentityFile ~/.ssh/<name-of-our-private-key-file>

        """.format(name=meta['name'])))
        exit(1)


class Sync:
    def __init__(self, cmd):
        self.cmd = cmd

    def uploads(self):
        print('Downloading uploads from server...')
        self.__runcmd(
            '"{name}:/home/{name}/app/wp-content/uploads/" "{root}/wp-content/uploads"'.
            format(name=meta['name'], root=dirs.root_dir))

    def plugins(self):
        paths = '"{name}:/home/{name}/app/wp-content/plugins/{plugin}" "{root}/wp-content/plugins"'
        for plugin in meta['plugins']:
            self.__runcmd(paths.format(name=meta['name'], plugin=plugin))

    def theme(self):
        self.__runcmd(
            '"{name}:/home/{name}/app/wp-content/themes/{theme}" "{root}/wp-content/plugins"'.
            format(
                name=meta['name'],
                theme=meta['base_theme'],
                root=dirs.root_dir))

    def database(self):
        pass

    def __runcmd(self, paths):
        os.system('{command} {options} {paths}'.format(
            command=self.cmd[0], options=self.cmd[1], paths=paths))


def main():
    prechecks()
    sync = Sync(ssh_init())
    sync.plugins()


main()
