#!/usr/bin/env python3.6

import argparse
import os

from shared import dirs, prechecks, server_meta, ssh_init

meta = server_meta()

parser = argparse.ArgumentParser()
parser.add_argument(
    '-i',
    '--init',
    help='Syncs everything. Run this on initial setup',
    action='store_true')
parser.add_argument(
    '-u', '--uploads', help='Sync uploads', action='store_true')
parser.add_argument(
    '-p', '--plugins', help='Sync plugins', action='store_true')
parser.add_argument('-t', '--theme', help='Sync theme', action='store_true')
parser.add_argument(
    '-d', '--database', help='Sync database', action='store_true')
args = parser.parse_args()


class Sync:
    def __init__(self, cmd):
        self.cmd = cmd
        self.root_dir = dirs.root_dir()

    def uploads(self):
        print('Downloading uploads from server...')
        self.__runcmd(
            '"{name}:/home/{name}/app/wp-content/uploads/" "{root}/wp-content/uploads"'.
            format(name=meta['name'], root=self.root_dir))

    def plugins(self):
        print('Downloading plugins from server...')
        paths = '"{name}:/home/{name}/app/wp-content/plugins/{plugin}" "{root}/wp-content/plugins"'
        for plugin in meta['plugins']:
            print('--> Downloading plugin {}'.format(plugin))
            self.__runcmd(
                paths.format(
                    name=meta['name'], plugin=plugin, root=self.root_dir))

    def theme(self):
        print('Downloading theme from server...')
        self.__runcmd(
            '"{name}:/home/{name}/app/wp-content/themes/{theme}" "{root}/wp-content/plugins"'.
            format(
                name=meta['name'],
                theme=meta['base_theme'],
                root=self.root_dir))

    def database(self):
        pass

    def __runcmd(self, paths):
        os.system('{command} {options} {paths}'.format(
            command=self.cmd[0], options=self.cmd[1], paths=paths))


def main():
    prechecks()
    sync = Sync(ssh_init())
    sync.uploads()


main()
